[package]
name = "boxxy"
version = "0.3.0"
description = "Linkable sandbox explorer"
authors = ["kpcyrd <git@rxv.cc>"]
license = "LGPL-3.0"
repository = "https://github.com/kpcyrd/boxxy-rs"
categories = ["command-line-interface", "development-tools::debugging"]
readme = "README.md"

[lib]
crate-type = ["lib", "dylib", "staticlib"]

[badges]
travis-ci = { repository = "kpcyrd/boxxy-rs" }

[features]
default = ["network"]
network = ["hyper", "hyper-rustls", "tokio-core", "futures"]

[dependencies]
rustyline = "1.0.0"
log = "0.3"
clap = { version = "2", default-features = false }
libc = "0.2"
errno = "0.2"
regex = "0.2"
nix = "0.9"
base64 = "0.7"
cfg-if = "0.1"
rustls = { version = "0.11", features = ["dangerous_configuration"] }
bufstream = "0.1"
rust-crypto = "0.2"
webpki = "0.17"

hyper = { version = "0.11", optional = true }
hyper-rustls = { version = "0.11", optional = true }
tokio-core = { version = "0.1", optional = true }
futures = { version = "0.1", optional = true }

[dev-dependencies]
env_logger = "0.4"
elf = "0.0.10"
