[package]
name = "boxxy"
version = "0.3.0"
description = "Linkable sandbox explorer"
authors = ["kpcyrd <git@rxv.cc>"]
license = "LGPL-3.0"
repository = "https://github.com/kpcyrd/boxxy-rs"
categories = ["command-line-interface", "development-tools::debugging"]
readme = "README.md"

[lib]
crate-type = ["lib", "dylib", "staticlib"]

[badges]
travis-ci = { repository = "kpcyrd/boxxy-rs" }

[dependencies]
rustyline = "1.0.0"
log = "0.3"
clap = { version = "2", default-features = false }
libc = "0.2"
errno = "0.2"
regex = "0.2"
nix = "0.9"
base64 = "0.7"
cfg-if = "0.1"
bufstream = "0.1"

[dev-dependencies]
env_logger = "0.4"
elf = "0.0.10"
